### ISSUE TITLE
修改长度后不能验证

### ISSUE THREAD

**Issue by ntdiary** [whvcse/EasyCaptcha#2]
修改验证码长度为4位时，这里的顺序好像会导致返回前端的是4位，但服务端存储的还是5位
![image](https://user-images.githubusercontent.com/8579651/40279097-620e4864-5c6f-11e8-8637-b0089f738326.png)

**Comment by whvcse** [comment]
已解决，这个项目开始并没有终点维护，因为有好几个开源项目，最近已经对这个项目重新整理，优化了一些代码，感谢使用！
