### ISSUE TITLE
验证码乱码如何解决？

### ISSUE THREAD

**Issue by shadowf1end** [whvcse/EasyCaptcha#3]
用的是阿里云

**Comment by whvcse** [comment]
可能是字体的原因吧，但是我的项目也在阿里云部署，就没有这个问题，http://47.98.107.251:8089/login，这是我的项目，在linux上的字体只是跟Windows稍微有些不一样，但是不会乱码，这个项目之前没有重点维护，最新重新优化了一些，感谢使用！
