### ISSUE TITLE
支持的Java版本

### ISSUE THREAD

**Issue by pengcheng789** [whvcse/EasyCaptcha#5]
作者你好，谢谢你贡献这个成果！在查看使用文档的时候，我发现没有提及该库支持的Java版本，我想知道它支持JDK 11吗？因为之前我使用过一个很老的验证码库，它在linux系统的JDK 11环境下会因为字体文件问题出错。

**Comment by whvcse** [comment]
跟JDK应该没有多大关系，主要是你的linux系统没有安装Arial字体，安装一下就可以了
